# Generated by Django 2.2.6 on 2019-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191025_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
