# Generated by Django 2.2.6 on 2019-10-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notifications_is_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='persona_name',
            new_name='person_name',
        ),
    ]
