# Generated by Django 2.2.6 on 2019-10-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191025_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='image_capture',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
