# Generated by Django 2.2.6 on 2019-11-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='camera',
        ),
        migrations.AddField(
            model_name='notifications',
            name='camera_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
